// front end/components/newsletter.tsx
"use client"

import { useState } from "react"
import { motion } from "framer-motion"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { useToast } from "@/components/ui/use-toast"

export function Newsletter() {
  const [email, setEmail] = useState("")
  const [isLoading, setIsLoading] = useState(false)
  const { toast } = useToast()

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    setIsLoading(true)
    // Here you would typically send the email to your backend
    console.log("Subscribing email:", email)
    await new Promise((resolve) => setTimeout(resolve, 1000)) // Simulating API call
    setIsLoading(false)
    toast({
      title: "Subscribed!",
      description: "You've successfully subscribed to our newsletter.",
    })
    setEmail("")
  }

  return (
    <section className="py-20 bg-gray-900 text-white">
      <div className="container mx-auto px-4">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6 }}
          className="max-w-2xl mx-auto text-center"
        >
          <h2 className="text-3xl md:text-4xl font-bold mb-6">Stay in the Loop</h2>
          <p className="text-gray-300 mb-8">
            Subscribe to our newsletter for exclusive deals, new releases, and sneaker news.
          </p>
          <form onSubmit={handleSubmit} className="flex flex-col sm:flex-row gap-4">
            <Input
              type="email"
              placeholder="Enter your email"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              className="flex-grow"
              required
            />
            <Button type="submit" className="gradient-bg" disabled={isLoading}>
              {isLoading ? "Subscribing..." : "Subscribe"}
            </Button>
          </form>
        </motion.div>
      </div>
    </section>
  )
}

// frontend/src/components/Newsletter.vue
<template>
  <section class="py-20 bg-gray-900 text-white">
    <div class="container mx-auto px-4">
      <div class="max-w-2xl mx-auto text-center">
        <h2 class="text-3xl md:text-4xl font-bold mb-6">Stay in the Loop</h2>
        <p class="text-gray-300 mb-8">
          Subscribe to our newsletter for exclusive deals, new releases, and sneaker news.
        </p>
        <form @submit.prevent="handleSubmit" class="flex flex-col sm:flex-row gap-4">
          <input
            type="email"
            v-model="email"
            placeholder="Enter your email"
            class="flex-grow px-4 py-2 rounded-lg focus:outline-none focus:ring-2 focus:ring-orange-500"
            required
          />
          <button
            type="submit"
            :disabled="isLoading"
            class="bg-gradient-to-r from-orange-500 to-orange-600 text-white px-6 py-2 rounded-lg hover:from-orange-600 hover:to-orange-700 transition-all duration-300 disabled:opacity-50"
          >
            {{ isLoading ? "Subscribing..." : "Subscribe" }}
          </button>
        </form>
      </div>
    </div>
  </section>
</template>

<script>
import { ref } from 'vue'
import { useNewsletterStore } from '@/store/newsletter'

export default {
  name: 'Newsletter',
  setup() {
    const email = ref('')
    const isLoading = ref(false)
    const newsletterStore = useNewsletterStore()

    const handleSubmit = async () => {
      isLoading.value = true
      try {
        await newsletterStore.subscribe(email.value)
        alert("You've successfully subscribed to our newsletter!")
        email.value = ''
      } catch (error) {
        alert('An error occurred while subscribing. Please try again.')
      } finally {
        isLoading.value = false
      }
    }

    return {
      email,
      isLoading,
      handleSubmit
    }
  }
}
</script>
