// frontend/app/about/page.tsx
import { Navbar } from "@/components/navbar"
import Footer from "@/components/footer"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import Image from "next/image"

export default function AboutPage() {
  return (
    <>
      <Navbar />
      <main className="container mx-auto px-4 py-16 mt-16">
        <h1 className="text-4xl font-bold text-center mb-8">About Stride by Marlow</h1>
        <Card className="mb-8">
          <CardHeader>
            <CardTitle>Our Story</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="flex flex-col md:flex-row items-center gap-8">
              <div className="md:w-1/2">
                <p className="text-lg mb-4">
                  Stride by Marlow was founded in 2020 with a simple mission: to provide high-quality, stylish sneakers
                  to sneaker enthusiasts in Kenya and beyond. Our journey began in a small workshop in Nairobi, where we
                  crafted our first pair of sneakers with meticulous attention to detail and a commitment to quality.
                </p>
                <p className="text-lg">
                  Today, we've grown into a beloved brand, known for our innovative designs and dedication to customer
                  satisfaction. We continue to push the boundaries of sneaker technology while staying true to our roots
                  of craftsmanship and style.
                </p>
              </div>
              <div className="md:w-1/2">
                <Image
                  src="/about-image.jpg"
                  alt="Stride by Marlow workshop"
                  width={500}
                  height={300}
                  className="rounded-lg"
                />
              </div>
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardHeader>
            <CardTitle>Our Values</CardTitle>
          </CardHeader>
          <CardContent>
            <ul className="list-disc list-inside space-y-2">
              <li>Quality craftsmanship in every pair</li>
              <li>Innovative design that pushes boundaries</li>
              <li>Customer satisfaction as our top priority</li>
              <li>Sustainability in our materials and processes</li>
              <li>Supporting local communities and artisans</li>
            </ul>
          </CardContent>
        </Card>
      </main>
      <Footer />
    </>
  )
}

// frontend/src/views/About.vue
<template>
  <div class="container mx-auto px-4 py-8">
    <h1 class="text-3xl font-bold mb-8">About Stride by Marlow</h1>
    <div class="flex flex-col md:flex-row gap-8">
      <div class="md:w-1/2">
        <img src="" alt="Stride by Marlow team" class="w-full h-auto rounded-lg shadow-lg">
      </div>
      <div class="md:w-1/2">
        <h2 class="text-2xl font-semibold mb-4">Our Story</h2>
        <p class="mb-4">
          Stride by Marlow was founded in 2020 by a group of passionate sneaker enthusiasts who believed that
          everyone deserves to walk in comfort and style. Our journey began in a small workshop in Nairobi, where
          we crafted our first pair of sneakers with meticulous attention to detail and a commitment to quality.
        </p>
        <p class="mb-4">
          Today, we've grown into a beloved brand, known for our innovative designs and dedication to customer
          satisfaction. We continue to push the boundaries of sneaker technology while staying true to our roots
          of craftsmanship and style.
        </p>
        <h2 class="text-2xl font-semibold mb-4">Our Mission</h2>
        <p class="mb-4">
          At Stride by Marlow, our mission is to provide our customers with the perfect blend of style, comfort,
          and performance. We believe that the right pair of sneakers can elevate your everyday experiences,
          whether you're hitting the gym, exploring the city, or simply going about your day.
        </p>
        <h2 class="text-2xl font-semibold mb-4">Our Values</h2>
        <ul class="list-disc list-inside mb-4">
          <li>Quality craftsmanship</li>
          <li>Innovative design</li>
          <li>Customer satisfaction</li>
          <li>Sustainability</li>
          <li>Community engagement</li>
        </ul>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  name: 'About'
}
</script>
