// app/contact/page.tsx
"use client"

import type React from "react"

import { useState } from "react"
import { Button } from "@/components/ui/button"
import { Mail, Phone, MapPin } from "lucide-react"

export default function ContactPage() {
  const [formData, setFormData] = useState({
    name: "",
    email: "",
    subject: "",
    message: "",
  })

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault()
    console.log("Form submitted:", formData)
    setFormData({ name: "", email: "", subject: "", message: "" })
  }

  return (
    <div className="container-max py-12">
      <div className="max-w-4xl mx-auto">
        <h1 className="text-5xl font-bold mb-6">Contact Us</h1>
        <p className="text-lg text-muted-foreground mb-12">
          Have a question? We're here to help. Reach out to us and we'll respond as soon as possible.
        </p>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-12">
          {/* Contact Info */}
          <div className="space-y-8">
            <div className="flex gap-4">
              <div className="w-12 h-12 bg-accent rounded-lg flex items-center justify-center flex-shrink-0">
                <Mail className="text-accent-foreground" size={20} />
              </div>
              <div>
                <h3 className="font-semibold mb-1">Email</h3>
                <p className="text-muted-foreground">support@stridemarlow.com</p>
              </div>
            </div>

            <div className="flex gap-4">
              <div className="w-12 h-12 bg-accent rounded-lg flex items-center justify-center flex-shrink-0">
                <Phone className="text-accent-foreground" size={20} />
              </div>
              <div>
                <h3 className="font-semibold mb-1">Phone</h3>
                <p className="text-muted-foreground">+254 (0) 123 456 789</p>
              </div>
            </div>

            <div className="flex gap-4">
              <div className="w-12 h-12 bg-accent rounded-lg flex items-center justify-center flex-shrink-0">
                <MapPin className="text-accent-foreground" size={20} />
              </div>
              <div>
                <h3 className="font-semibold mb-1">Location</h3>
                <p className="text-muted-foreground">Nairobi, Kenya</p>
              </div>
            </div>
          </div>

          {/* Contact Form */}
          <form onSubmit={handleSubmit} className="space-y-4">
            <div>
              <label className="block text-sm font-semibold mb-2">Name</label>
              <input
                type="text"
                value={formData.name}
                onChange={(e) => setFormData({ ...formData, name: e.target.value })}
                className="w-full px-4 py-2 border border-border rounded-lg bg-input text-foreground placeholder-muted-foreground"
                placeholder="Your name"
                required
              />
            </div>

            <div>
              <label className="block text-sm font-semibold mb-2">Email</label>
              <input
                type="email"
                value={formData.email}
                onChange={(e) => setFormData({ ...formData, email: e.target.value })}
                className="w-full px-4 py-2 border border-border rounded-lg bg-input text-foreground placeholder-muted-foreground"
                placeholder="your@email.com"
                required
              />
            </div>

            <div>
              <label className="block text-sm font-semibold mb-2">Subject</label>
              <input
                type="text"
                value={formData.subject}
                onChange={(e) => setFormData({ ...formData, subject: e.target.value })}
                className="w-full px-4 py-2 border border-border rounded-lg bg-input text-foreground placeholder-muted-foreground"
                placeholder="Subject"
                required
              />
            </div>

            <div>
              <label className="block text-sm font-semibold mb-2">Message</label>
              <textarea
                value={formData.message}
                onChange={(e) => setFormData({ ...formData, message: e.target.value })}
                className="w-full px-4 py-2 border border-border rounded-lg bg-input text-foreground placeholder-muted-foreground resize-none"
                placeholder="Your message"
                rows={5}
                required
              ></textarea>
            </div>

            <Button type="submit" className="w-full bg-accent hover:bg-accent/90 text-accent-foreground py-2">
              Send Message
            </Button>
          </form>
        </div>
      </div>
    </div>
  )
}

// frontend/src/views/Contact.vue
<template>
  <div class="container mx-auto px-4 py-8">
    <h1 class="text-3xl font-bold mb-8">Contact Us</h1>
    <div class="flex flex-col md:flex-row gap-8">
      <div class="md:w-1/2">
        <h2 class="text-2xl font-semibold mb-4">Get in Touch</h2>
        <form @submit.prevent="submitForm" class="space-y-4">
          <div>
            <label for="name" class="block mb-1">Name</label>
            <input type="text" id="name" v-model="form.name" required class="w-full border rounded px-3 py-2">
          </div>
          <div>
            <label for="email" class="block mb-1">Email</label>
            <input type="email" id="email" v-model="form.email" required class="w-full border rounded px-3 py-2">
          </div>
          <div>
            <label for="message" class="block mb-1">Message</label>
            <textarea id="message" v-model="form.message" required class="w-full border rounded px-3 py-2 h-32"></textarea>
          </div>
          <button type="submit" class="bg-orange-500 text-white px-6 py-3 rounded-lg hover:bg-orange-600 transition-colors duration-300">
            Send Message
          </button>
        </form>
      </div>
      <div class="md:w-1/2">
        <h2 class="text-2xl font-semibold mb-4">Contact Information</h2>
        <p class="mb-2"><strong>Address:</strong> Imenti House, First Floor, Stall No: A19, Nairobi, Kenya</p>
        <p class="mb-2"><strong>Phone:</strong> +254 714470576</p>
        <p class="mb-2"><strong>Email:</strong> info@stridemarlow.com</p>
        <h3 class="text-xl font-semibold mt-6 mb-2">Business Hours</h3>
        <p class="mb-2">Monday - Friday: 9:00 AM - 6:00 PM</p>
        <p class="mb-2">Saturday: 10:00 AM - 4:00 PM</p>
        <p class="mb-2">Sunday: Closed</p>
      </div>
    </div>
  </div>
</template>

<script>
import { ref } from 'vue'
import { useContactStore } from '@/store/contact'

export default {
  name: 'Contact',
  setup() {
    const contactStore = useContactStore()
    const form = ref({
      name: '',
      email: '',
      message: ''
    })

    const submitForm = async () => {
      try {
        await contactStore.sendMessage(form.value)
        alert('Thank you for your message. We will get back to you soon!')
        form.value = { name: '', email: '', message: '' }
      } catch (error) {
        console.error('Error sending message:', error)
        alert('An error occurred while sending your message. Please try again.')
      }
    }

    return {
      form,
      submitForm
    }
  }
}
</script>
